os: Linux
dist: focal

language: python
python:
  - "3.8"

cache: pip

env:
  global:
    - DOCKER_REPONAME=lbnlblum
    - OMC_VERSION=ubuntu-2204-omc:1.22.0_dev-41-g8a5b18f-1
    - MODELICA_BUILDINGS_VERSION=9.1.0
    - MODELICA_JSON_VERSION=ac5580f720b553617cde76996d1d56d4b4e28cc0
    - MODELICAPATH=${TRAVIS_BUILD_DIR}/modelica-buildings
    - MODELICAJSONPATH=${TRAVIS_BUILD_DIR}/modelica-json

notifications:
  email: false

git:
  depth: 10

# Install dependencies
# graphviz is required by plantuml
addons:
  apt:
    packages:
    - graphviz

before_install:
  - chmod +x software/verification/travis/omc
  - docker pull ${DOCKER_REPONAME}/${OMC_VERSION};
    cp software/verification/travis/omc $HOME/bin/omc;
  -  wget --no-verbose https://github.com/lbl-srg/modelica-json/archive/${MODELICA_JSON_VERSION}.tar.gz;
      tar xzf ${MODELICA_JSON_VERSION}.tar.gz;
      rm ${MODELICA_JSON_VERSION}.tar.gz;
      mv modelica-json-${MODELICA_JSON_VERSION} ${MODELICAJSONPATH};
      cd ${MODELICAJSONPATH};
      make install-node-packages;
      make compile;
      cd -;
      echo "Installed modelica-json in ${MODELICAJSONPATH}";
  - wget --no-verbose https://github.com/lbl-srg/modelica-buildings/archive/refs/tags/v${MODELICA_BUILDINGS_VERSION}.tar.gz;
      tar xzf modelica-buildings-${MODELICA_BUILDINGS_VERSION}.tar.gz;
      rm modelica-buildings-${MODELICA_BUILDINGS_VERSION}.tar.gz;
      mv modelica-buildings-${MODELICA_BUILDINGS_VERSION} ${MODELICAPATH};
      cd ${MODELICAPATH};
      cd -;
      echo "Set up modelica-buildings at ${MODELICAPATH}";

install:
  - pip3 install --upgrade pip wheel

# Execute tests
script:
  - |
    cd specification
    python -m venv venv
    source venv/bin/activate
    pip install -r ${TRAVIS_BUILD_DIR}/specification/requirements.txt
    make clean html
    make latex
    make linkcheck SPHINXOPTS=-W
    deactivate
    rm -rf venv
  - |
    cd software/verification
    python -m venv venv
    source venv/bin/activate
    pip install -r ${TRAVIS_BUILD_DIR}/software/verification/requirements.txt
    make test-verification
    deactivate
    rm -rf venv
