os: Linux
dist: focal

language: python
python:
  - "3.8"

cache: pip

env:
  global:
    - OMC_VERSION=ubuntu-2004-omc:1.19.0_dev-539-gb76366f-1
    - MODELICA_BUILDINGS_VERSION=8.1.0
    - MODELICA_JSON_VERSION=ac5580f720b553617cde76996d1d56d4b4e28cc0
    - MODELICAPATH=${TRAVIS_BUILD_DIR}/modelica-buildings
    - MODELICAJSONPATH=${TRAVIS_BUILD_DIR}/modelica-json

notifications:
  email: false

git:
  depth: 10

# Install dependencies
# graphviz is required by plantuml
addons:
  apt:
    packages:
    - graphviz

before_install:
  - chmod +x software/verification/travis/omc
  - docker pull michaelwetter/${OMC_VERSION};
    cp software/verification/travis/omc $HOME/bin/omc;
  -  wget --no-verbose https://github.com/lbl-srg/modelica-json/archive/${MODELICA_JSON_VERSION}.tar.gz;
      tar xzf ${MODELICA_JSON_VERSION}.tar.gz;
      rm ${MODELICA_JSON_VERSION}.tar.gz;
      mv modelica-json-${MODELICA_JSON_VERSION} ${MODELICAJSONPATH};
      cd ${MODELICAJSONPATH};
      make install-node-packages;
      make compile;
      cd -;
      echo "Installed modelica-json in ${MODELICAJSONPATH}";
  - wget --no-verbose https://github.com/lbl-srg/modelica-buildings/archive/refs/tags/v${MODELICA_BUILDINGS_VERSION}.tar.gz;
      tar xzf modelica-buildings-${MODELICA_BUILDINGS_VERSION}.tar.gz;
      rm modelica-buildings-${MODELICA_BUILDINGS_VERSION}.tar.gz;
      mv modelica-buildings-${MODELICA_BUILDINGS_VERSION} ${MODELICAPATH};
      cd ${MODELICAPATH};
      cd -;
      echo "Set up modelica-buildings at ${MODELICAPATH}";

# For sphinx, we need to install specific package versions, otherwise
# the html output may have small formatting differences which causes
# the test to fail
install:
  - pip3 install --upgrade pip wheel
  - pip3 install sphinx==4.3.2 \
      sphinx-bootstrap-theme==0.8.0 \
      sphinxcontrib-bibtex==2.4.1 \
      sphinxcontrib-plantuml==0.22 \
      alabaster==0.7.12 \
      MarkupSafe==1.1.1 \
      Pygments==2.4.2 \
      snowballstemmer==1.9.0 \
      docutils==0.17.1 \
      Babel==2.7.0 \
      requests==2.27.0 \
      Jinja2==2.11.3 \
      latexcodec==1.0.7 \
      pybtex==0.24.0 \
      pybtex-docutils==1.0.1 \
      oset==0.1.3 \
      PyYAML==5.4
  - pip3 install -r ${TRAVIS_BUILD_DIR}/software/verification/requirements.txt

# Execute tests
script:
  - (cd specification; make clean html; cd ..)
  - (cd specification; make latex; cd ..)
  - (cd specification; make linkcheck SPHINXOPTS=-W; cd ..)
  - (cd software/verification; make test-verification; cd ../..)
