os: Linux
dist: focal

language: python
python:
  - "3.8"

cache: pip

notifications:
  email: false

git:
  depth: 10

# Install dependencies
# graphviz is required by plantuml
addons:
  apt:
    packages:
    - graphviz

# For sphinx, we need to install specific package versions, otherwise
# the html output may have small formatting differences which causes
# the test to fail
install:
  - pip3 install --upgrade pip wheel
  - pip3 install sphinx==4.3.2 \
      sphinx-bootstrap-theme==0.8.0 \
      sphinxcontrib-bibtex==2.4.1 \
      sphinxcontrib-plantuml==0.22 \
      alabaster==0.7.12 \
      MarkupSafe==1.1.1 \
      Pygments==2.4.2 \
      snowballstemmer==1.9.0 \
      docutils==0.17.1 \
      Babel==2.7.0 \
      requests==2.27.0 \
      Jinja2==2.10.1 \
      latexcodec==1.0.7 \
      pybtex==0.24.0
      pybtex-docutils==1.0.1 \
      oset==0.1.3 \
      PyYAML==5.4

# Execute tests
script:
  - (cd specification; make clean html; cd ..)
  - (cd specification; make latex; cd ..)
  - (cd specification; make linkcheck SPHINXOPTS=-W; cd ..)
