#!/usr/bin/python
# -*- coding: utf-8 -*-
import os, sys
from io import open
print(sys.version)

oldFil=os.path.join("build", "latex", "cdl_report.tex")
newFil=os.path.join("build", "latex", "cdl_report.tex-new")

def freplace(old, new):
    with open(oldFil, mode="rt", encoding="utf-8") as fin, open(newFil, mode="wt", encoding="utf-8") as fout:
        for line in fin:
            fout.write(line.replace(old, new))
    os.remove(oldFil)
    os.rename(newFil, oldFil)

freplace('\documentclass[letterpaper,10pt,english]{report}', '''\pdfminorversion=7
\documentclass[letterpaper, 10pt, english]{report}''')

# This removes code generated by sphinx which causes on Ubuntu 16.04
# a  "LaTeX Error: Option clash for package geometry." because we
# overwrite the geometry settings.
freplace('\usepackage[margin=1in,marginparwidth=0.5in]{geometry}', '') # for Linux
freplace('\usepackage{geometry}', '')                                  # for OS X

freplace('\\maketitle',
        '\\input{../../source/titlepage.tex} \\setcounter{page}{2}')

freplace('\\phantomsection\\label{index::doc}',
        '\\phantomsection\\label{index::doc} \\clearpage')

freplace('\\begin{thebibliography}{1}',
        '''\\chapter{References}
\\begin{thebibliography}{1}''')

freplace('\\begin{Verbatim}[',
        '\\begin{Verbatim}[fontsize=\\footnotesize, ')

freplace('\\begin{longtable}{|l|l|}',
         '\\begin{longtable}{|*{2}{p{\\dimexpr(\\linewidth-\\arrayrulewidth)/2-2\\tabcolsep-\\arrayrulewidth\\relax}|}}')
